include: package:lints/recommended.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    # Enforce good Dart style
    - prefer_single_quotes
    - require_trailing_commas
    - sort_child_properties_last 